# Generated by Django 4.2.6 on 2023-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("created", models.DateField(auto_now_add=True)),
                ("deadline", models.DateField(blank=True)),
                ("completed", models.BooleanField()),
                ("tags", models.ManyToManyField(related_name="tasks", to="tasks.tag")),
            ],
        ),
    ]
