# Generated by Django 4.2.6 on 2023-10-28 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed", "-created"]},
        ),
    ]
